on:
  push:
    branches: [main]
    tags: ['*']

jobs:
  tests-node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: node
      - uses: biomejs/setup-biome@v2
        with:
          version: latest
      - run: corepack enable
      - run: pnpm i -D

      - name: lint
        run: biome lint .

      - name: build
        run: pnpm build

      - name: test
        run: pnpm test

      - name: pack
        run: pnpm pack

      - uses: actions/upload-artifact@v4
        with:
          name: '@benricheson101-util-pkg'
          path: ./benricheson101-util-*.tgz

  release:
    runs-on: ubuntu-latest
    needs: tests-node
    # if: ${{github.ref_type == 'tag'}}
    if: contains(github.ref, 'refs/tags/')

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: node
      - uses: biomejs/setup-biome@v2
        with:
          version: latest
      - run: corepack enable
      - run: pnpm i -D

      - name: build
        run: pnpm build

      - name: publish
        run: pnpm publish --no-git-checks --access public
        env:
          NPM_TOKEN: '${{secrets.NPM_TOKEN}}'
